packages:
  - packages/*
  - engine-plugins/*
catalog:
  "@apidevtools/json-schema-ref-parser": ^11.7.2
  "@codemirror/autocomplete": ^6.18.1
  "@codemirror/commands": ^6.7.0
  "@codemirror/lang-javascript": ^6.2.2
  "@codemirror/lang-json": ^6.0.1
  "@codemirror/lang-yaml": ^6.1.1
  "@codemirror/language": ^6.10.3
  "@codemirror/lint": ^6.8.2
  "@codemirror/search": ^6.5.6
  "@codemirror/state": ^6.4.1
  "@codemirror/view": ^6.34.1
  "@dagrejs/dagre": ^1.1.4
  "@dnd-kit/core": ^6.1.0
  "@dnd-kit/modifiers": ^7.0.0
  "@dnd-kit/sortable": ^8.0.0
  "@dnd-kit/utilities": ^3.2.2
  "@esbuild-plugins/node-globals-polyfill": ^0.2.3
  "@esbuild-plugins/node-modules-polyfill": ^0.2.2
  "@eslint/js": ^9.12.0
  "@go-task/cli": ^3.39.2
  "@radix-ui/react-accordion": ^1.2.1
  "@radix-ui/react-dialog": ^1.1.2
  "@radix-ui/react-popover": ^1.1.2
  "@radix-ui/react-select": ^2.1.2
  "@radix-ui/react-switch": ^1.1.1
  "@radix-ui/react-toggle-group": ^1.1.0
  "@radix-ui/react-tooltip": ^1.1.3
  "@stepci/runner": ^2.0.7
  "@stoplight/json-schema-sampler": ^0.3.0
  "@tailwindcss/container-queries": ^0.1.1
  "@tanstack/eslint-plugin-query": ^5.59.7
  "@tanstack/react-query": ^5.59.15
  "@tanstack/react-table": ^8.20.5
  "@tauri-apps/api": ^2.1.1
  "@tauri-apps/cli": ^2.1.0
  "@tauri-apps/plugin-dialog": ^2.0.1
  "@tauri-apps/plugin-fs": ^2.0.2
  "@tauri-apps/plugin-http": ^2.0.1
  "@tauri-apps/plugin-shell": ^2.0.1
  "@types/d3-hierarchy": ^3.1.7
  "@types/js-yaml": ^4.0.9
  "@types/json-schema": ^7.0.15
  "@types/node": ^22.8.1
  "@types/react-dom": ^18.3.1
  "@types/wicg-file-system-access": ^2023.10.5
  "@vitest/eslint-plugin": ^1.1.7
  "@xyflow/react": ^12.3.2
  ajv: ^8.17.1
  autoprefixer: ^10.4.20
  buffer: ^6.0.3
  client-zip: ^2.4.5
  clsx: ^2.1.1
  codemirror: ^6.0.1
  core-js: ^3.38.1
  effect: ^3.9.2
  elkjs: ^0.9.3
  eslint: ^9.12.0
  eslint-config-flat-gitignore: ^0.3.0
  eslint-config-prettier: ^9.1.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsx-a11y: ^6.10.0
  eslint-plugin-react: ^7.37.1
  eslint-plugin-react-hooks: 5.1.0-rc-fb9a90fa48-20240614
  eslint-plugin-react-refresh: ^0.4.12
  eslint-plugin-unused-imports: ^4.1.4
  fuzzysort: ^3.1.0
  jotai-devtools: ^0.10.1
  js-yaml: ^4.1.0
  monaco-editor: ^0.52.0
  nanoid: ^5.0.7
  npm-run-all: ^4.1.5
  openapi3-ts: ^4.4.0
  prettier: ^3.3.3
  prettier-plugin-tailwindcss: ^0.6.8
  quicktype: ^23.0.170
  react: ^18.3.1
  react-dom: ^18.3.1
  react-hook-form: ^7.53.0
  react-icons: ^5.3.0
  rollup-plugin-visualizer: ^5.12.0
  tailwindcss: ^3.4.14
  thememirror: ^2.0.1
  typescript-eslint: ^8.9.0
  vitest: ^2.1.3
