name: lint_format

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.1
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
      - name: Run lint and formatter
        run: pnpm run check
